import batou.component
import batou.lib.file


class HTTPBasicAuth(batou.component.Component):
    """
    A glueing component for managing http_basic_auth auth strings.

    This component _does not_ generate the htpasswd string itself, but
    requires a pre-compiled one (stored into secrets). You may use

    mkpasswd -R 100000 -m sha-512 <password> <salt>

    for generating the passwordsection. General structure of entry is like
    <username>:<generated_password_string>

    Usage:
    from batou_ext.http import HTTPBasicAuth

    self += batou_ext.http.HTTPBasicAuth(
        username="joe",
        password="secret",
        basic_auth_string="joe:$apr1$Ma0Fc6pW$Kl5dV4ecBXH12gDieRHVq.")

    Alternativ if you want to use Flyingcircus' autogenerated http_auth
    file based on project configuration just use:

    self += batou_ext.http.HTTPBasicAuth(fcio_auth=True)
    """

    fcio_auth = batou.component.Attribute("literal", False)
    username = None
    password = None
    basic_auth_string = None

    def configure(self):
        self.provide("http_basic_auth", self)
        if self.fcio_auth:
            self.path = "/etc/local/nginx/htpasswd_fcio_users"
        else:
            self._deploy_customer_http_auth_file()

    def _deploy_customer_http_auth_file(self):
        self += batou.lib.file.File("htpasswd_portal", content=self.basic_auth_string)
        self.path = self._.path
