name: Unit tests

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull request events:
  push:
    branches: [ master ]
  pull_request:

  # Allow to run this workflow manually from the Actions tab:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

# The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test
        run: tox -e py
