name: publish batou_ext to pypi
on: push

jobs:
  build:
    name: build batou_ext
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python3 -m pip install build --user
      - run: python3 -m build
      - name: store the artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/


  publish-to-pypi:
    name: Publish batou_ext to pypi
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/batou_ext
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish batou_ext to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
